<?php
    // Conditions
    define('CONDITION_EQUAL', 1);
    define('CONDITION_NOT_EQUAL', 2);
    define('CONDITION_GREATER_THEN_EQUAL', 3);
    define('CONDITION_GREATER_THEN', 4);
    define('CONDITION_LESS_THEN_EQUAL', 5);
    define('CONDITION_LESS_THEN', 6);
    define('CONDITION_BETWEEN', 7);
    define('CONDITION_NOT_BETWEEN', 8);
    define('CONDITION_IN', 9);
    define('CONDITION_NOT_IN', 10);

    // Report
    define('EXPORT_DNC_REPORT_LIMIT', 100000);
    define('EXPORT_CALL_REPORT_ID', 1);
    define('EXPORT_CALL_REPORT_FILE_NAME', 'export_call_report_%s_%s_%s.csv');
    define('EXPORT_CALL_REPORT_FILE_NAME_FORMAT', 'export_call_report_%s_%s_%s.%s');
    define('EXPORT_LEAD_REPORT_ID', 2);
    define('EXPORT_LEAD_REPORT_FILE_NAME', 'export_lead_report_%s_%s_%s.csv');
    define('INBOUND_REPORT_ID', 3);
    define('INBOUND_BY_DID_REPORT_ID', 4);
    define('INBOUND_SERVICE_LEVEL_REPORT_ID', 5);
    define('INBOUND_SUMMARY_HOURLY_REPORT_ID', 6);
    define('INBOUND_DAILY_REPORT_ID', 7);
    define('INBOUND_DID_REPORT_ID', 8);
    define('INBOUND_IVR_REPORT_ID', 9);
    define('OUTBOUND_CALLING_REPORT_ID', 10);
    define('OUTBOUND_SUMMARY_INTERVAL_REPORT_ID', 11);
    define('OUTBOUND_IVR_REPORT_ID', 12);
    define('FRONTER_CLOSER_REPORT_ID', 13);
    define('LISTS_CAMPAIGN_STATUSES_REPORT_ID', 14);
    define('CAMPAIGN_STATUS_LIST_REPORT_ID', 15);
    define('AGENT_TIME_REPORT_ID', 16);
    define('AGENT_STATUS_REPORT_ID', 17);
    define('AGENT_PERFORMANCE_REPORT_ID', 18);
    define('TEAM_PERFORMANCE_REPORT_ID', 19);
    define('SINGLE_AGENT_REPORT_ID', 20);
    define('USER_GROUP_LOGIN_REPORT_ID', 21);
    define('USER_STATS_REPORT_ID', 22);
    define('USER_TIME_SHEET_REPORT_ID', 23);
    define('AGENT_LOGIN_REPORT_ID', 24);
    define('USER_TIMECLOCK_REPORT_ID', 25);
    define('USER_GROUP_TIMECLOCK_STATUS_REPORT_ID', 26);
    define('USER_TIMECLOCK_DETAIL_REPORT_ID', 27);
    define('OUTBOUND_IVR_EXPORT_REPORT_ID', 28);
    define('PERFORMANCE_COMPARISON_REPORT_ID', 29);
    // -- DNC
    define('DNC_REPORT_ID', 900);

    //custom report for particular customer 
    define('CUSTOM_AGENT_REPORT_DB_ID', 1781);

    // System Component
    // -- Dashboard
    define('SYSTEM_COMPONENT_DASHBOARD_REALTIME', 16);
    define('SYSTEM_COMPONENT_DASHBOARD_CAMPAIGN', 63);
    // -- User
    define('SYSTEM_COMPONENT_USER_USER', 14);
    define('SYSTEM_COMPONENT_USER_USER_GROUP', 15);
    // -- Campaign
    define('SYSTEM_COMPONENT_CAMPAIGN_CAMPAIGN', 7);
    define('SYSTEM_COMPONENT_CAMPAIGN_CAMAPIGN_STATUS', 8);
    define('SYSTEM_COMPONENT_CAMPAIGN_CAMPAIGN_LIST_MIX', 9);
    define('SYSTEM_COMPONENT_CAMPAIGN_LEAD_RECYCLE', 10);
    define('SYSTEM_COMPONENT_CAMPAIGN_PAUSE_CODE', 11);
    define('SYSTEM_COMPONENT_CAMPAIGN_AC_CID', 12);
    define('SYSTEM_COMPONENT_CAMPAIGN_CALL_TRANSFER_PRESENT', 13);
    // -- Data Management
    define('SYSTEM_COMPONENT_DATA_MANAGEMENT_DATA_LIST', 17);
    define('SYSTEM_COMPONENT_DATA_MANAGEMENT_DATA_LIST_DOWNLOAD', 67);
    define('SYSTEM_COMPONENT_DATA_MANAGEMENT_ADVANCED_LIST_RULE', 18);
    // -- -- Data Loader
    define('SYSTEM_COMPONENT_DATA_LOADER_ACCESS', 5);
    define('SYSTEM_COMPONENT_DATA_LOADER_DATA_FILE', 1);
    define('SYSTEM_COMPONENT_DATA_LOADER_PROCESS_FILE', 2);
    define('SYSTEM_COMPONENT_DATA_LOADER_ERROR_FILE', 3);
    define('SYSTEM_COMPONENT_DATA_LOADER_QUEUE', 4);
    // --
    define('SYSTEM_COMPONENT_DATA_MANAGEMENT_DATA_SEARCH', 19);
    define('SYSTEM_COMPONENT_DATA_MANAGEMENT_CUSTOM_FIELD', 20);
    define('SYSTEM_COMPONENT_DATA_MANAGEMENT_LEAD_MANAGEMENT', 21);
    // -- Inbound
    define('SYSTEM_COMPONENT_INBOUND_INBOUND_QUEUE', 22);
    define('SYSTEM_COMPONENT_INBOUND_NUMBER', 23);
    define('SYSTEM_COMPONENT_INBOUND_CALL_MENU', 24);
    define('SYSTEM_COMPONENT_INBOUND_FILTER_PHONE_GROUP', 25);
    define('SYSTEM_COMPONENT_INBOUND_AGENT', 71);
    // -- Admin Utility
    define('SYSTEM_COMPONENT_ADMIN_SCRIPT', 26);
    define('SYSTEM_COMPONENT_ADMIN_AUDIO', 27);
    define('SYSTEM_COMPONENT_ADMIN_VOICEMAIL', 28);
    define('SYSTEM_COMPONENT_ADMIN_DNC', 29);
    define('SYSTEM_COMPONENT_ADMIN_LEAD_FILTER_LIST', 30);
    define('SYSTEM_COMPONENT_ADMIN_CALL_TIME', 31);
    define('SYSTEM_COMPONENT_ADMIN_SHIFT', 32);
    define('SYSTEM_COMPONENT_ADMIN_SYSTEM_AUDIT', 33);
    define('SYSTEM_COMPONENT_ADMIN_SYSTEM_STATUS', 64);
    define('SYSTEM_COMPONENT_ADMIN_MOH', 65);
    define('SYSTEM_COMPONENT_ADMIN_RECORDINGS', 69);
    // -- Report
    define('SYSTEM_COMPONENT_REPORT_EXPORT_CALL', 34);
    define('SYSTEM_COMPONENT_REPORT_EXPORT_LEAD', 35);
    define('SYSTEM_COMPONENT_REPORT_INBOUND', 36);
    define('SYSTEM_COMPONENT_REPORT_INBOUND_BY_DID', 37);
    define('SYSTEM_COMPONENT_REPORT_INBOUND_SERVICE_LEVEL', 38);
    define('SYSTEM_COMPONENT_REPORT_INBOUND_SUMMARY_HOURLY', 39);
    define('SYSTEM_COMPONENT_REPORT_INBOUND_DAILY', 40);
    define('SYSTEM_COMPONENT_REPORT_INBOUND_DID', 41);
    define('SYSTEM_COMPONENT_REPORT_INBOUND_IVR', 42);
    define('SYSTEM_COMPONENT_REPORT_OUTBOUND_CALLING', 43);
    define('SYSTEM_COMPONENT_REPORT_OUTBOUND_SUMMARY_INTERVAL', 44);
    define('SYSTEM_COMPONENT_REPORT_OUTBOUND_IVR', 45);
    define('SYSTEM_COMPONENT_REPORT_FRONTER_CLOSER', 46);
    define('SYSTEM_COMPONENT_REPORT_LISTS_CAMPAIGN_STATUSES', 47);
    define('SYSTEM_COMPONENT_REPORT_CAMPAIGN_STATUS_LIST', 48);
    define('SYSTEM_COMPONENT_REPORT_AGENT_TIME', 49);
    define('SYSTEM_COMPONENT_REPORT_AGENT_STATUS', 50);
    define('SYSTEM_COMPONENT_REPORT_AGENT_PERFORMANCE', 51);
    define('SYSTEM_COMPONENT_REPORT_TEAM_PERFORMANCE', 52);
    define('SYSTEM_COMPONENT_REPORT_SINGLE_AGENT', 53);
    define('SYSTEM_COMPONENT_REPORT_USER_GROUP_LOGIN', 54);
    define('SYSTEM_COMPONENT_REPORT_USER_STATS', 55);
    define('SYSTEM_COMPONENT_REPORT_USER_TIME_SHEET', 56);
    define('SYSTEM_COMPONENT_REPORT_AGENT_LOGIN', 57);
    define('SYSTEM_COMPONENT_REPORT_USER_TIMECLOCK', 58);
    define('SYSTEM_COMPONENT_REPORT_USER_GROUP_TIMECLOCK_STATUS', 59);
    define('SYSTEM_COMPONENT_REPORT_USER_TIMECLOCK_DETAIL', 60);
    define('SYSTEM_COMPONENT_REPORT_OUTBOUND_IVR_EXPORT', 61);
    define('SYSTEM_COMPONENT_REPORT_PERFORMANCE_COMPARISON', 62);
    define('SYSTEM_COMPONENT_REPORT_CAMPAIGN_LIST_DETAIL', 68);
    // -- APP
    define('SYSTEM_COMPONENT_APP_LEADBEAM', 66);
    define('SYSTEM_COMPONENT_APP_LEADBEAM2', 70);

    // -- DNC
//    define('DNC_ACCESS', 6);


    // Product Type
    define('PRODUCT_TYPE_VOICE_ANALYTICS', 28);
    define('PRODUCT_TYPE_MULTI_CHANNELS', 29);
    define('PRODUCT_TYPE_X6', 30);
    define('PRODUCT_TYPE_CAMPAIGN_LIST_DETAIL', 40);

    // App ID
    define('APP_MULTI_CHANNELS', 29);
    define('APP_CAMPAIGN_LIST_DETAIL_REPORT', 40);
    define('APP_DATALOADER_AUTOMATION', 41);
    define('APP_LEADBEAM2', 70);
    define('APP_CALL_CRITERIA_INTEGRATION', 42);


    // Voice Analytics
    define('VOICE_ANALYTICS_SEARCH_PRIORITY_KEYWORDS_MATCH', 1);
    define('VOICE_ANALYTICS_SEARCH_PRIORITY_KEYWORDS_COUNT', 2);

    // Notification
    define('NOTIFICATION_DISABLE', 0);

    define('NOTIFICATION_CONDITIONS_AND', 1);
    define('NOTIFICATION_CONDITIONS_OR', 2);

    define('NOTIFICATION_METHOD_EMAIL', 1);
    define('NOTIFICATION_METHOD_SMS', 2);
    define('NOTIFICATION_METHOD_CALL', 3);
    define('NOTIFICATION_METHOD_PUSH', 4);


    // Access
    define('ACCESS_OVERWRITE_FULL', 800);

    define('ACCESS_MODEL_CONTACT', 1);
    define('ACCESS_MODEL_CONTACTGROUP', 2);
    define('ACCESS_MODEL_CONTACT_BY_CONTACTGROUP', 3);

    define('ACCESS_TYPE_CAMPAIGN', 1);
    define('ACCESS_TYPE_USERGROUP', 2);
    define('ACCESS_TYPE_INGROUP', 3);
    define('ACCESS_TYPE_CALLMENU', 4);
    define('ACCESS_TYPE_USER', 5);
    define('ACCESS_TYPE_LIST', 6);
    define('ACCESS_TYPE_REPORT', 7);
    define('ACCESS_TYPE_RECORDING', 10);
    define('ACCESS_TYPE_SYSTEM_COMPONENT', 100);
    define('ACCESS_TYPE_X5_CONTACT_GROUP', 999);

    define('ACCESS_LINKID_ALL', '_');

    define('ACCESS_CREATE', '_create');
    define('ACCESS_READ', '_read');
    define('ACCESS_UPDATE', '_update');
    define('ACCESS_DELETE', '_delete');

    define('X5_CONTACT_GROUP_TYPE_SYSTEM', 1);
    define('X5_CONTACT_GROUP_TYPE_USER_CREATE', 2);

    define('RETURN_ALL_SELECTOR', true);
    define('NOT_RETURN_ALL_SELECTOR', false);
    define('ALLOW_NULL', true);
    define('NOT_ALLOW_NULL', false);

    // X5 Contact Token Type
    define('RESET_PASSWORD_TOKEN_TYPE', 100);

    // X6
    define('X6_COMPONENT_SMS', 1);
    define('X6_COMPONENT_EMAIL', 2);

    define('X6_LINK_TYPE_ALL', 1);


    // Data Loader
    define('DATALOADER_AUTO_MAX', 10);

    define('DATALOADER_AUTO_TYPE_AUTO_LOAD_LEAD_CAMPAIGN_LEAD_BELOW_THRESHOLD', 1);
    define('DATALOADER_AUTO_TYPE_AUTO_LOAD_LEAD_LIST_LEAD_BELOW_THRESHOLD', 2);

    define('DATALOADER_AUTO_STATUS_NOT_READY', 0);
    define('DATALOADER_AUTO_STATUS_READY', 1);
    define('DATALOADER_AUTO_STATUS_RUNNING', 2);
    define('DATALOADER_AUTO_STATUS_ERROR', 4);

    define('DATALOADER_AUTO_POST_TYPE_BEFORE_DOWNLOAD', 1);
    define('DATALOADER_AUTO_POST_TYPE_DOWNLOAD_LEAD', 2);
    define('DATALOADER_AUTO_POST_TYPE_AFTER_DOWNLOAD', 3);
    define('DATALOADER_AUTO_POST_TYPE_AFTER_PROCESSED', 4);

    define('DATALOADER_AUTO_POST_METHOD_GET', 1);
    define('DATALOADER_AUTO_POST_METHOD_POST', 2);


    // X5 Contact Link Type
    define('X5_CONTACT_LINK_TYPE_COMPANY', 'company_id');
    define('X5_CONTACT_LINK_TYPE_ADMIN_PHONE', 'vici_admin_phone');

    // Application ID
    define('APPLICATION_ID_X5', 6);

    // DB Type
    define('DB_TYPE_MYSQL', 1);


    // Ytel X5 extra setting
    define('YTEL_EXTRA_SETTING_DEFAULT_LEAD_PREVIEW', 'default_lead_preview');

    // Report cron
    define('STATUS_NOT_READY', 0);
    define('STATUS_READY', 1);
    define('STATUS_RUNNING', 2);
    define('STATUS_SUCCESS', 3);
    define('STATUS_ERROR', 4);

    define('REPORT_CRON_ADDED', 'REPORT_CRON_ADDED');

    //path
    define("CSV_PATH", "../storage/csvfiles/");